apiVersion: apps/v1
kind: Deployment
metadata:
  name: emi
  namespace: emi
spec:
  replicas: 6
  selector:
    matchLabels:
      app: emi
  template:
    metadata:
      labels:
        app: emi
    spec:
      containers:
        - name: emi
          image: emi:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: emi-service
  namespace: emi
spec:
  selector:
    app: emi
  ports:
    - nodePort: 32520
      protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
